export interface Broker {
  uuid: string;
  slug: string;
  domain?: string | null;
  rank?: number | null;
  name: string;
  score?: number | null;
  legal_name?: string | null;
  founded_approx?: string | null;
  hq_country?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  affiliate_url?: string | null;
  regulation?: string[] | null;
  regulation_tier?: string | null;
  platforms?: string[] | null;
  eur_usd_spread?: number | null;
  min_deposit?: number | null;
  max_leverage?: number | null;
  commission?: string | null;
  instruments?: string | null;
  account_type?: string[] | null;
  color?: string | null;
  status?: string | null;
  warning_reason?: string | null;
  description?: string | null;
  quick_verdict?: string | null;
  pros?: string[] | null;
  cons?: string[] | null;
  spreads_from?: string | null;
  spreads_note?: string | null;
  withdrawal_time?: string | null;
  withdrawal_note?: string | null;
  copy_trading?: string | null;
  copy_trading_note?: string | null;
  demo_account?: string | null;
  demo_account_note?: string | null;
  min_deposit_note?: string | null;
  leverage_note?: string | null;
  regulation_note?: string | null;
  broker_type_note?: string | null;
  instruments_note?: string | null;
  founded_note?: string | null;
  platform_note?: string | null;
  payment_methods?: string[] | null;
  trust_pilot_score?: string | null;
  awards?: string[] | null;
  trust_signals?: string[] | null;
  offer_title?: string | null;
  offer_desc?: string | null;
  offer_note?: string | null;
  offer_url?: string | null;
  offer_label?: string | null;
  is_published?: boolean | null;
  deleted_at?: string | null;
  created_at?: string;
  updated_at?: string;
}